### ISSUE TITLE
运行时候有几个报错请教下

### ISSUE THREAD

**Issue by lingshengjiang** [huangshayang/SpringBootApiTest#2]
环境：Mac、 jdk11
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.security.AccessController.doPrivileged(AccessController.java:310) ~[?:?]
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:213) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:171) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:213) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:201) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.HashedWheelTimer.<clinit>(HashedWheelTimer.java:89) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:169) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:532) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:233) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration.lettuceClientResources(LettuceConnectionConfiguration.java:67) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration$$EnhancerBySpringCGLIB$$d045194f.CGLIB$lettuceClientResources$0(<generated>) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration$$EnhancerBySpringCGLIB$$d045194f$$FastClassBySpringCGLIB$$f1ee19bb.invoke(<generated>) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration$$EnhancerBySpringCGLIB$$d045194f.lettuceClientResources(<generated>) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

[2019-07-06 12:48:29] - [main] - [DEBUG] - io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:372) - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3ff7bfd2
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:355) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:639) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:559) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]

**Comment by huangshayang** [comment]
@lingshengjiang   这个报错不影响使用  我google了也没找到解决办法
